# Generated by Django 5.1.7 on 2025-03-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la película')),
                ('autor', models.CharField(max_length=100, verbose_name='Director/Autor')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('duracion_minutos', models.PositiveIntegerField(verbose_name='Duración (minutos)')),
                ('genero', models.CharField(max_length=100, verbose_name='Género')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/', verbose_name='Portada')),
            ],
        ),
    ]
