# Generated by Django 5.1.7 on 2025-03-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='descripcion_ampliada',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción ampliada'),
        ),
    ]
